version: 2.1
jobs:
  lint:
    docker:
      - image: cimg/node:20.15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm install
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
      - run:
          command: npm run lint
  test:
    docker:
      - image: cimg/node:20.15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run test
  build:
    docker:
      - image: cimg/node:20.15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: npm run build
  deploy_preview:
    docker:
      - image: cimg/node:20.15
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install Vercel CLI
          command: npm install --global vercel@latest
      - run:
          name: Pull Vercel Environment Information
          command: vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
      - run:
          name: Deploy to Vercel preview
          command: vercel deploy --prebuilt --token=$VERCEL_TOKEN

workflows:
  version: 2
  test_and_lint:
    jobs:
      - lint
      - test:
          requires:
            - lint
      - build:
          requires:
            - test
      - deploy_preview:
          requires:
            - build
          filters:
            branches:
              ignore:
                - main
